### ISSUE TITLE
采用该插件无法从Kafka中获取数据写入Doris

### ISSUE THREAD

**Issue by howlshadow** [apache/doris-kafka-connector#10]
测试环境：Kafka Connect集群，日志为Debezium的PostgresConnector产生，avro格式；Doris版本为 doris-2.0.2-rc05；

将下载的jar包，放入connect-distributed.properties指定的plugin.path中，重启后插件生效，kafka集群连接器插件列表返回如下信息：
![image](https://github.com/apache/doris-kafka-connector/assets/76094105/daa0a69f-8bac-416d-8d4d-d053f2600880)

按照文档提示，正常可以创建connector，配置信息如下：
![image](https://github.com/apache/doris-kafka-connector/assets/76094105/f650a9e7-8651-411c-862d-97a555b5a95c)

发送消息到Kafka后，完整消息体格式如下：
![image](https://github.com/apache/doris-kafka-connector/assets/76094105/77eaef9b-59c7-40c3-876d-28dad9ce4099)

connect.log中信息如下：
![image](https://github.com/apache/doris-kafka-connector/assets/76094105/cbd5fc87-fceb-4549-892d-453c1879a877)

be.INFO中信息如下：
![image](https://github.com/apache/doris-kafka-connector/assets/76094105/55d35756-8a11-46ca-a1f4-4a4c565e4288)

**Comment by DongLiang-0** [comment]
https://github.com/apache/doris-kafka-connector/pull/11
https://github.com/apache/doris-kafka-connector/pull/12
