### ISSUE TITLE
配置普通AVRO schema

### ISSUE THREAD

**Issue by fairyto2** [apache/doris-kafka-connector#29]
示例中AVRO只写了io.confluent的registry.url版本，请问是否支持普通的AVRO schema，或者在配置中直接指定schema？

**Comment by DongLiang-0** [comment]
Currently, the schema cannot be specified. 
If you have such a need, you can add me on WeChat to chat: Shake9988

**Comment by fairyto2** [comment]
**需求：** 
1. 希望支持apache avro的序列化及反序列化过程；
2. 希望支持配置中指定schema方式，不使用reigister url。
**注：** apache avro与confluent avro的数据二进制定义有所不同，无法兼容。
**配置示例：**
``` JSON
{
"value.converter": "com.xxx.AvroConverter", // 自定义converter
"value.converter.schema.schemaString":"{\"type\":\"record\",\"name\":\"test_schema\",\"namespace\":\"test_schema\",\"fields\":[{\"name\":\"test_array\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}],\"default\":null},{\"name\":\"test_string\",\"type\":[\"null\",\"string\"],\"default\":null}]}",
} // schema字符串
```
